### ISSUE TITLE
Queue sent messages 

### ISSUE THREAD

**Issue by luisloaiza** [Criptext/MonkeyKit-JS#1]
Manage all sent messages in a queue and confirm sent messages with ACK.

Use a cookie for this.

**Comment by luisloaiza** [comment]
We need to use a secure storage, not sure if using cookies.

BUT i will reference this issue https://github.com/Criptext/Criptext-Web-Messaging/issues/102

**Comment by GianniCarlo** [comment]
Already completed 👍. But this only applies for text messages, not media
